<?xml version="1.0" encoding="utf-8"?>
<!-- Copyright (c) 2018, The Linux Foundation. All rights reserved.

SPDX-License-Identifier: Linux-OpenIB
-->
<!DOCTYPE manifest [
<!ELEMENT manifest (hal)>
<!ATTLIST manifest version NMTOKEN #REQUIRED>
<!ATTLIST manifest type NMTOKEN #REQUIRED>
<!ELEMENT hal (name,transport,version,interface)>
<!ATTLIST hal format NMTOKEN #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT transport (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT interface (name,instance)>
<!ELEMENT instance (#PCDATA)>]>
<manifest version="1.0" type="device">
    <!-- Codec2 HAl service -->
    <hal format="hidl">
        <name>android.hardware.media.c2</name>
        <transport>hwbinder</transport>
        <version>1.0</version>
        <interface>
            <name>IComponentStore</name>
            <instance>default</instance>
        </interface>
    </hal>
</manifest>