<?xml version="1.0" encoding="UTF-8"?>
<!-- Bluetooth Audio HAL Audio Policy Configuration file -->
<!DOCTYPE module [
<!ELEMENT module (mixPorts,devicePorts,routes)>
<!ATTLIST module name NMTOKEN #REQUIRED>
<!ATTLIST module halVersion NMTOKEN #REQUIRED>
<!ELEMENT mixPorts (mixPort)>
<!ELEMENT mixPort (profile)>
<!ATTLIST mixPort name CDATA #REQUIRED>
<!ATTLIST mixPort role NMTOKEN #REQUIRED>
<!ELEMENT profile EMPTY>
<!ATTLIST profile name CDATA #REQUIRED>
<!ATTLIST profile format NMTOKEN #REQUIRED>
<!ATTLIST profile samplingRates CDATA #REQUIRED>
<!ATTLIST profile channelMasks NMTOKEN #REQUIRED>
<!ELEMENT devicePorts (devicePort)>
<!ELEMENT devicePort EMPTY>
<!ATTLIST devicePort tagName CDATA #REQUIRED>
<!ATTLIST devicePort type NMTOKEN #REQUIRED>
<!ATTLIST devicePort role NMTOKEN #REQUIRED>
<!ELEMENT routes (route)>
<!ELEMENT route EMPTY>
<!ATTLIST route type NMTOKEN #REQUIRED>
<!ATTLIST route sink CDATA #REQUIRED>
<!ATTLIST route sources CDATA #REQUIRED>]>
<module name="bluetooth" halVersion="2.0">
    <mixPorts>
        <!-- Hearing AIDs Audio Ports -->
        <mixPort name="hearing aid output" role="source">
            <profile name="" format="AUDIO_FORMAT_PCM_16_BIT"
                     samplingRates="24000 16000"
                     channelMasks="AUDIO_CHANNEL_OUT_STEREO"/>
        </mixPort>
    </mixPorts>
    <devicePorts>
        <!-- Hearing AIDs Audio Ports -->
        <devicePort tagName="BT Hearing Aid Out" type="AUDIO_DEVICE_OUT_HEARING_AID" role="sink"/>
    </devicePorts>
    <routes>
        <route type="mix" sink="BT Hearing Aid Out"
               sources="hearing aid output"/>
    </routes>
</module>